In [13]:
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import os
import pandas as pd
import seaborn as sns
import time
plt.style.use('ggplot')

%matplotlib inline

In [28]:
empl_df = pd.read_csv("nyc-employment.csv",names=['Dates','Employment (Per Thousands of Person)'])
#removing headers
empl_df = empl_df.ix[1:]
empl_df

          Dates Employment (Per Thousands of Person)
1    2006-01-01                               3647.9
2    2006-02-01                               3652.1
3    2006-03-01                               3664.6
4    2006-04-01                               3671.5
5    2006-05-01                               3677.7
6    2006-06-01                               3682.7
7    2006-07-01                               3682.4
8    2006-08-01                               3680.4
9    2006-09-01                               3695.4
10   2006-10-01                               3701.7
11   2006-11-01                               3713.9
12   2006-12-01                               3725.3
13   2007-01-01                               3733.4
14   2007-02-01                               3742.3
15   2007-03-01                               3748.2
16   2007-04-01                               3745.6
17   2007-05-01                               3750.9
18   2007-06-01                               3760.1
19   2007-07-01                               3761.5
20   2007-08-01                               3764.1
21   2007-09-01                               3771.0
22   2007-10-01                               3783.0
23   2007-11-01                               3790.1
24   2007-12-01                               3793.0
25   2008-01-01                               3807.6
26   2008-02-01                               3815.0
27   2008-03-01                               3815.1
28   2008-04-01                               3822.7
29   2008-05-01                               3818.5
30   2008-06-01                               3821.3
..          ...                                  ...
91   2013-07-01                               4003.6
92   2013-08-01                               4010.1
93   2013-09-01                               4021.9
94   2013-10-01                               4037.4
95   2013-11-01                               4050.5
96   2013-12-01                               4057.9
97   2014-01-01                               4062.6
98   2014-02-01                               4075.7
99   2014-03-01                               4084.4
100  2014-04-01                               4100.6
101  2014-05-01                               4115.0
102  2014-06-01                               4126.9
103  2014-07-01                               4138.6
104  2014-08-01                               4156.2
105  2014-09-01                               4163.0
106  2014-10-01                               4171.9
107  2014-11-01                               4186.2
108  2014-12-01                               4196.1
109  2015-01-01                               4206.5
110  2015-02-01                               4214.7
111  2015-03-01                               4219.7
112  2015-04-01                               4221.4
113  2015-05-01                               4237.1
114  2015-06-01                               4253.0
115  2015-07-01                               4255.5
116  2015-08-01                               4265.1
117  2015-09-01                               4275.0
118  2015-10-01                               4291.8
119  2015-11-01                               4300.5
120  2015-12-01                               4306.4

[120 rows x 2 columns]

In [31]:
empl_df['Dates'] = pd.to_datetime(empl_df['Dates'], coerce=True)

empl_df['Employment (Per Thousands of Person)'] = empl_df['Employment (Per Thousands of Person)'].astype(float)
empl_df.dtypes
empl_df

/Users/syedalishehryar/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: the coerce=True keyword is deprecated, use errors='coerce' instead
  if __name__ == '__main__':

         Dates  Employment (Per Thousands of Person)
1   2006-01-01                                3647.9
2   2006-02-01                                3652.1
3   2006-03-01                                3664.6
4   2006-04-01                                3671.5
5   2006-05-01                                3677.7
6   2006-06-01                                3682.7
7   2006-07-01                                3682.4
8   2006-08-01                                3680.4
9   2006-09-01                                3695.4
10  2006-10-01                                3701.7
11  2006-11-01                                3713.9
12  2006-12-01                                3725.3
13  2007-01-01                                3733.4
14  2007-02-01                                3742.3
15  2007-03-01                                3748.2
16  2007-04-01                                3745.6
17  2007-05-01                                3750.9
18  2007-06-01                                3760.1
19  2007-07-01                                3761.5
20  2007-08-01                                3764.1
21  2007-09-01                                3771.0
22  2007-10-01                                3783.0
23  2007-11-01                                3790.1
24  2007-12-01                                3793.0
25  2008-01-01                                3807.6
26  2008-02-01                                3815.0
27  2008-03-01                                3815.1
28  2008-04-01                                3822.7
29  2008-05-01                                3818.5
30  2008-06-01                                3821.3
..         ...                                   ...
91  2013-07-01                                4003.6
92  2013-08-01                                4010.1
93  2013-09-01                                4021.9
94  2013-10-01                                4037.4
95  2013-11-01                                4050.5
96  2013-12-01                                4057.9
97  2014-01-01                                4062.6
98  2014-02-01                                4075.7
99  2014-03-01                                4084.4
100 2014-04-01                                4100.6
101 2014-05-01                                4115.0
102 2014-06-01                                4126.9
103 2014-07-01                                4138.6
104 2014-08-01                                4156.2
105 2014-09-01                                4163.0
106 2014-10-01                                4171.9
107 2014-11-01                                4186.2
108 2014-12-01                                4196.1
109 2015-01-01                                4206.5
110 2015-02-01                                4214.7
111 2015-03-01                                4219.7
112 2015-04-01                                4221.4
113 2015-05-01                                4237.1
114 2015-06-01                                4253.0
115 2015-07-01                                4255.5
116 2015-08-01                                4265.1
117 2015-09-01                                4275.0
118 2015-10-01                                4291.8
119 2015-11-01                                4300.5
120 2015-12-01                                4306.4

[120 rows x 2 columns]

In [58]:
import bokeh.io, bokeh.plotting, bokeh.models, bokeh.charts
from bokeh.models import DatetimeTickFormatter
bokeh.io.output_notebook()
from bokeh.layouts import gridplot
from bokeh.plotting import figure, show, output_file
#p1 = bokeh.plotting.figure()
#p.circle(empl_df['Dates'], empl_df['Employment (Per Thousands of Person)'])
#p.line(empl_df['Dates'],empl_df['Employment (Per Thousands of Person)'])
#bokeh.plotting.show(p)

#p = figure(x_axis_type="datetime", title="Stock Closing Prices")
#p1.grid.grid_line_alpha=0.3
#p1.xaxis.axis_label = 'Date'
#p1.yaxis.axis_label = 'Price'

#p1.line(datetime(AAPL['date']), AAPL['adj_close'], color='#A6CEE3', legend='AAPL')
#p.line(empl_df['Dates'], empl_df['Employment (Per Thousands of Person)'])
#p.xaxis.formatter=DatetimeTickFormatter(
        
#     years=["%d %B %Y"],
 #   )
#p.xaxis.major_label_orientation = pi/4
#output_file('myplot.html')
#show(p)


p1 = figure(x_axis_type="datetime", title=" NYC Employment - 2006 to 2015")
p1.grid.grid_line_alpha=0.3
p1.xaxis.axis_label = 'Year'
p1.yaxis.axis_label = 'Employment (Per Thousands of Person)'
p1.xaxis[0].ticker.desired_num_ticks = 10 #adjust the number of ticks for time axis

p1.line(empl_df['Dates'], empl_df['Employment (Per Thousands of Person)'], color='#B2DF8A',line_width = 3)

show(p1)